### ISSUE TITLE
did you ask permission from the original creators to include these?

### ISSUE THREAD

**Issue by DeckOfNoobs** [MCMiners9/ConversionTools#1]
Just sayin'. it's a good idea since I asked permission for BrawlBox in the aio

**Comment by MCMiners9** [comment]
Even if I didn't I placed a note at the bottom of [this link](https://github.com/MCMiners9/ConversionTools) for everyone to credit them for making the tools

**Comment by MCMiners9** [comment]
But I might want to just to make sure that I am allowed to create a repository for it.
